### ISSUE TITLE
关于SAMPoluBuild代码的问题

### ISSUE THREAD

**Issue by dyzy41** [wchh-2000/SAMPolyBuild#1]
作者您好，关于您的代码我有2点问题？
1. test.py代码中似乎没有导入训练好的模型，我猜测这里可能缺了部分代码。
2. 请问一下这份代码做推理的时候，需要输入点或者框的prompt吗？

感谢

**Comment by labiao** [comment]
> 作者您好，关于您的代码我有2点问题？
> 
> 1. test.py代码中似乎没有导入训练好的模型，我猜测这里可能缺了部分代码。
> 2. 请问一下这份代码做推理的时候，需要输入点或者框的prompt吗？
> 
> 感谢

似乎还有一些问题，configs文件中提供的配置文件都是基于prompt mode的，关于auto mode 的配置文件好像没有提供。另外，模型部分是否有提供 auto bbox prompt 模块相关的代码？

**Comment by wchh-2000** [comment]
> 作者您好，关于您的代码我有2点问题？
> 
> 1. test.py代码中似乎没有导入训练好的模型，我猜测这里可能缺了部分代码。
> 2. 请问一下这份代码做推理的时候，需要输入点或者框的prompt吗？
> 
> 感谢

1.如下图，build_sam中会加载args中的训练好的权重文件checkpoint 
![image](https://github.com/user-attachments/assets/6acb6060-395d-493c-a88a-e4351d97ce95)

2.数据集标注中含有框(bbox)字段，会用bbox和bbox中心点作为提示，在[dataset](https://github.com/wchh-2000/SAMPolyBuild/tree/master/dataset)/dataset_crop.py ‎PromptDataset中加载。

**Comment by wchh-2000** [comment]
> 似乎还有一些问题，configs文件中提供的配置文件都是基于prompt mode的，关于auto mode 的配置文件好像没有提供。另外，模型部分是否有提供 auto bbox prompt 模块相关的代码？

auto mode 代码是基于RSPrompter的，我们还在整理，以后会放出

**Comment by labiao** [comment]
> > 似乎还有一些问题，configs文件中提供的配置文件都是基于prompt mode的，关于auto mode 的配置文件好像没有提供。另外，模型部分是否有提供 auto bbox prompt 模块相关的代码？
> 
> auto mode 代码是基于RSPrompter的，我们还在整理，以后会放出

好的，感谢您的工作。

**Comment by labiao** [comment]
> > 作者您好，关于您的代码我有2点问题？
> > 
> > 1. test.py代码中似乎没有导入训练好的模型，我猜测这里可能缺了部分代码。
> > 2. 请问一下这份代码做推理的时候，需要输入点或者框的prompt吗？
> > 
> > 感谢
> 
> 1.如下图，build_sam中会加载args中的训练好的权重文件checkpoint ![image](https://private-user-images.githubusercontent.com/69345371/376599576-6acb6060-395d-493c-a88a-e4351d97ce95.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjkyMjgzNTMsIm5iZiI6MTcyOTIyODA1MywicGF0aCI6Ii82OTM0NTM3MS8zNzY1OTk1NzYtNmFjYjYwNjAtMzk1ZC00OTNjLWE4OGEtZTQzNTFkOTdjZTk1LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEwMTglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMDE4VDA1MDczM1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWRlYjQ0NGIxOTc0ZDY3OGZmMDlmNzNkOTZiMTA0MjRmZmYzYTRiNDQ4NjcwZGI4Y2M4ZmZjY2U4NGM1YWQ5N2EmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.VjaAf6JObSUmWzo0HAgDdeo5JDsWqHx0YEHjUviX4b4)
> 
> 2.数据集标注中含有框(bbox)字段，会用bbox和bbox中心点作为提示，在[dataset](https://github.com/wchh-2000/SAMPolyBuild/tree/master/dataset)/dataset_crop.py ‎PromptDataset中加载。

这是否意味着如果想预测一张没有标签的图像，代码做不了预测？

**Comment by wchh-2000** [comment]
> 那请问下，如果想预测一张没有bbox标签的图像，代码能实现吗？prompt_fullimg配置下预测时是否需要bbox标签呢？

如有需要，我们可以提供推理代码，输入影像，交互式点击获取框坐标，模型预测矢量轮廓。
prompt_fullimg配置下也需要bbox标签。fullimg指整个图像输入模型，而instance配置是只有实例区域图像输入模型。

**Comment by labiao** [comment]
> > 那请问下，如果想预测一张没有bbox标签的图像，代码能实现吗？prompt_fullimg配置下预测时是否需要bbox标签呢？
> 
> 如有需要，我们可以提供推理代码，输入影像，交互式点击获取框坐标，模型预测矢量轮廓。 prompt_fullimg配置下也需要bbox标签。fullimg指整个图像输入模型，而instance配置是只有实例区域图像输入模型。

好的，那麻烦您提供下推理代码供我学习。非常感谢。可发送至我邮箱：1725089507@qq.com

**Comment by wchh-2000** [comment]
> 好的，那麻烦您提供下推理代码供我学习。非常感谢。可发送至我邮箱：[1725089507@qq.com](mailto:1725089507@qq.com)

更新了代码，推理代码见infer_poly_crop.py，交互式提示推理interactive_prompt.py。

**Comment by wchh-2000** [comment]
> 似乎还有一些问题，configs文件中提供的配置文件都是基于prompt mode的，关于auto mode 的配置文件好像没有提供。另外，模型部分是否有提供 auto bbox prompt 模块相关的代码？

已经更新加入了自动模式的训练和测试
