### ISSUE TITLE
Release WHU-Mix dataset and corresponding config file

### ISSUE THREAD

**Issue by xiaomingwang80** [wchh-2000/SAMPolyBuild#3]
Hi, thank you for your good work!

I want to reproduce the result of the proposed method on WHU-Mix datasets. Is it possible to release the dataset and corresponding config file that you use in your paper? 

Thank you!

**Comment by wchh-2000** [comment]
> I want to reproduce the result of the proposed method on WHU-Mix datasets. Is it possible to release the dataset and corresponding config file that you use in your paper?
The WHU-Mix dataset configs and trained model has been uploaded, see new commit.
