### ISSUE TITLE
Please Release WHU-Mix  config file

### ISSUE THREAD

**Issue by lachaohaoxuexi** [wchh-2000/SAMPolyBuild#4]
Thanks for your great work! 
I noticed that in the training section you put the json file for spacenet into the config folder, can you please add the json file for the WHU-Mix dataset? Or can you tell how to generate the json file in the readme file?
Kind regards!

**Comment by wchh-2000** [comment]
> Thanks for your great work! I noticed that in the training section you put the json file for spacenet into the config folder, can you please add the json file for the WHU-Mix dataset? Or can you tell how to generate the json file in the readme file? Kind regards!

The config for WHU-Mix dataset has been uploaded.
