### ISSUE TITLE
Problems about Image Input Size

### ISSUE THREAD

**Issue by lachaohaoxuexi** [wchh-2000/SAMPolyBuild#5]
Limited by GPU training resources, setting the image input of the ViT architecture to 1024*1024 according to the settings in the paper will lead to "cuda out of memory"，but if we set ‘image_size" to 512 in the “Prompt_fullimg_spacenet.json” ,  in the next progress, using configs/auto_spacenet.py to train the auto mode will not be dimensionally correct and I guess testing and inference will also be affected,
can you offer some advice？(I don't know if it's possible to change the size of the input image to achieve training results)

Thank you!

**Comment by wchh-2000** [comment]
> Limited by GPU training resources, setting the image input of the ViT architecture to 1024*1024 according to the settings in the paper will lead to "cuda out of memory"，but if we set ‘image_size" to 512 in the “Prompt_fullimg_spacenet.json” , in the next progress, using configs/auto_spacenet.py to train the auto mode will not be dimensionally correct and I guess testing and inference will also be affected, can you offer some advice？(I don't know if it's possible to change the size of the input image to achieve training results)
>

If you set ‘image_size" to 512 in the “Prompt_fullimg_spacenet.json”, then you should add "image_size=512," in configs/bbox_prompter.py  model_cfg.backbone, and set "image_size = (512,512)" in configs/data_spacenet.py

**Comment by lachaohaoxuexi** [comment]
> > Limited by GPU training resources, setting the image input of the ViT architecture to 1024*1024 according to the settings in the paper will lead to "cuda out of memory"，but if we set ‘image_size" to 512 in the “Prompt_fullimg_spacenet.json” , in the next progress, using configs/auto_spacenet.py to train the auto mode will not be dimensionally correct and I guess testing and inference will also be affected, can you offer some advice？(I don't know if it's possible to change the size of the input image to achieve training results)
> 
> If you set ‘image_size" to 512 in the “Prompt_fullimg_spacenet.json”, then you should add "image_size=512," in configs/bbox_prompter.py model_cfg.backbone, and set "image_size = (512,512)" in configs/data_spacenet.py

After I set the img_size to 512 at your suggestion, everything works fine for training, and then I end up getting an error when I test it.The test code doesn't have a setting directly related to the image size, so would there need to be a change somewhere else to get the test to run properly?

Thank you for ur work and reply!
