### ISSUE TITLE
训练过程损失无穷大

### ISSUE THREAD

**Issue by Yiliud** [wchh-2000/SAMPolyBuild#6]
作者你好，在训自动模式之前要先用整张图训提示模式，在这个环节中，我的loss值是这样的：
Epoch 15: 60%|█████████ | 291/481 [01:59<01:17, 2.44it/s, v_num=1, train/vmap_loss=2.650, train/seg_loss=inf.0, val/mIoUmask=0.606, val/mIoU=0.562]
这里分割loss显示是无穷大，然后偶尔几个瞬间值为0.9或者0.8几，这是正常的吗？

**Comment by wchh-2000** [comment]
> 作者你好，在训自动模式之前要先用整张图训提示模式，在这个环节中，我的loss值是这样的： Epoch 15: 60%|█████████ | 291/481 [01:59<01:17, 2.44it/s, v_num=1, train/vmap_loss=2.650, train/seg_loss=inf.0, val/mIoUmask=0.606, val/mIoU=0.562] 这里分割loss显示是无穷大，然后偶尔几个瞬间值为0.9或者0.8几，这是正常的吗？

没有遇到过这种情况，看验证精度指标有问题吗？

**Comment by Yiliud** [comment]
> > 作者你好，在训自动模式之前要先用整张图训提示模式，在这个环节中，我的loss值是这样的： Epoch 15: 60%|█████████ | 291/481 [01:59<01:17, 2.44it/s, v_num=1, train/vmap_loss=2.650, train/seg_loss=inf.0, val/mIoUmask=0.606, val/mIoU=0.562] 这里分割loss显示是无穷大，然后偶尔几个瞬间值为0.9或者0.8几，这是正常的吗？
> 
> 没有遇到过这种情况，看验证精度指标有问题吗？

我也是将输入图片设成了512，512，但是测试似乎没跑通。请问改动输入图片大小时，测试需要改什么相应的吗？（训练auto mode也是能训的，但是感觉不正常）

**Comment by wchh-2000** [comment]
> > > 作者你好，在训自动模式之前要先用整张图训提示模式，在这个环节中，我的loss值是这样的： Epoch 15: 60%|█████████ | 291/481 [01:59<01:17, 2.44it/s, v_num=1, train/vmap_loss=2.650, train/seg_loss=inf.0, val/mIoUmask=0.606, val/mIoU=0.562] 这里分割loss显示是无穷大，然后偶尔几个瞬间值为0.9或者0.8几，这是正常的吗？
> > 
> > 
> > 没有遇到过这种情况，看验证精度指标有问题吗？
> 
> 我也是将输入图片设成了512，512，但是测试似乎没跑通。请问改动输入图片大小时，测试需要改什么相应的吗？（训练auto mode也是能训的，但是感觉不正常）

你的测试报错是什么？可以截图发上来

**Comment by Yiliud** [comment]
![log1](https://github.com/user-attachments/assets/1cc6796a-0afc-40a7-89f5-7051a54b318e)
![log2](https://github.com/user-attachments/assets/f9e84006-bb67-44f8-9e43-d6553af4f043)
除了图片大小按照之前的issue改了，别的没改动

**Comment by wchh-2000** [comment]
> ![log1](https://private-user-images.githubusercontent.com/130562147/393109698-1cc6796a-0afc-40a7-89f5-7051a54b318e.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzM0NjgzMDUsIm5iZiI6MTczMzQ2ODAwNSwicGF0aCI6Ii8xMzA1NjIxNDcvMzkzMTA5Njk4LTFjYzY3OTZhLTBhZmMtNDBhNy04OWY1LTcwNTFhNTRiMzE4ZS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMjA2JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTIwNlQwNjUzMjVaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1kNzg2ODM1ZTI1MzU0NjRkMjc4YTcwYjlmYjkyM2QyMzZjNThiYjM4Mzg0MWM0ODRmM2Y5ODExNDY2MTI4ZjYzJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.9G9yFqS-0zINNwwJrgVL28ySrZmz30yJoWUxh8N1coY) ![log2](https://private-user-images.githubusercontent.com/130562147/393109722-f9e84006-bb67-44f8-9e43-d6553af4f043.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzM0NjgzMDUsIm5iZiI6MTczMzQ2ODAwNSwicGF0aCI6Ii8xMzA1NjIxNDcvMzkzMTA5NzIyLWY5ZTg0MDA2LWJiNjctNDRmOC05ZTQzLWQ2NTUzYWY0ZjA0My5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMjA2JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTIwNlQwNjUzMjVaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT02ZjljYWIyZDU0ZGY2YTMwYzczODYzM2M4YWJmOGM3ZWQ5ZGVlMzg2YTQ0NzM4MTJlZjgzZjhiOWYwNzU2ZDcxJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.hAHnM0PWwEvVatMZrtrkywx1GZUocp-uiBcuxmzuMrY) 除了图片大小按照之前的issue改了，别的没改动

TypeError: COCOeval.summarize()got an unexpected keyword argument 'merge_sm'这个报错应该是因为没有安装本代码仓库文件夹中的pycocotools,这里加入了merge sm参数。
安装如下：
cd pycocotools/PythonAPI
pip install .

**Comment by Yiliud** [comment]
> > ![log1](https://private-user-images.githubusercontent.com/130562147/393109698-1cc6796a-0afc-40a7-89f5-7051a54b318e.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzM0NjgzMDUsIm5iZiI6MTczMzQ2ODAwNSwicGF0aCI6Ii8xMzA1NjIxNDcvMzkzMTA5Njk4LTFjYzY3OTZhLTBhZmMtNDBhNy04OWY1LTcwNTFhNTRiMzE4ZS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMjA2JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTIwNlQwNjUzMjVaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1kNzg2ODM1ZTI1MzU0NjRkMjc4YTcwYjlmYjkyM2QyMzZjNThiYjM4Mzg0MWM0ODRmM2Y5ODExNDY2MTI4ZjYzJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.9G9yFqS-0zINNwwJrgVL28ySrZmz30yJoWUxh8N1coY) ![log2](https://private-user-images.githubusercontent.com/130562147/393109722-f9e84006-bb67-44f8-9e43-d6553af4f043.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzM0NjgzMDUsIm5iZiI6MTczMzQ2ODAwNSwicGF0aCI6Ii8xMzA1NjIxNDcvMzkzMTA5NzIyLWY5ZTg0MDA2LWJiNjctNDRmOC05ZTQzLWQ2NTUzYWY0ZjA0My5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMjA2JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTIwNlQwNjUzMjVaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT02ZjljYWIyZDU0ZGY2YTMwYzczODYzM2M4YWJmOGM3ZWQ5ZGVlMzg2YTQ0NzM4MTJlZjgzZjhiOWYwNzU2ZDcxJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.hAHnM0PWwEvVatMZrtrkywx1GZUocp-uiBcuxmzuMrY) 除了图片大小按照之前的issue改了，别的没改动
> 
> TypeError: COCOeval.summarize()got an unexpected keyword argument 'merge_sm'这个报错应该是因为没有安装本代码仓库文件夹中的pycocotools,这里加入了merge sm参数。 安装如下： cd pycocotools/PythonAPI pip install .

感谢解答，测试跑通了。那个loss我可能是不知道改了什么，重新下了项目复现的时候loss又正常了。然后点数可能是由于设成512的原因要低一些。我回头用1024再复现一下。
